---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "iqserver.fullname" . }}-data
  namespace: jcava-dev-test-11
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "iqserver.fullname" . }}-log
  namespace: jcava-dev-test-11
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
