# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nexus-data-disk
#   namespace: jcava-dev-test-11
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: efs-sc
#   resources:
#     requests:
#       storage: 5Gi

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nexus-log-disk
#   namespace: jcava-dev-test-11
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: efs-sc
#   resources:
#     requests:
#       storage: 5Gi
